trigger:
- main

parameters:
- name: targetEnv
  type: string
  displayName: 'Target Environment'
  default: 'dev'
  values:
    - dev
    - qa
    - prod

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build Application Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Building application..."

- stage: DevDeploy
  displayName: 'Deploy to Dev'
  dependsOn: Build
  condition: and(succeeded(), eq('${{ parameters.targetEnv }}', 'dev'))
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo "Deploying to DEV environment"

- stage: QADeploy
  displayName: 'Deploy to QA'
  dependsOn: Build
  condition: and(succeeded(), eq('${{ parameters.targetEnv }}', 'qa'))
  jobs:
  - job: QADeployJob
    steps:
    - script: echo "Deploying to QA environment"

- stage: ProdDeploy
  displayName: 'Deploy to Prod'
  dependsOn: Build
  condition: and(succeeded(), eq('${{ parameters.targetEnv }}', 'prod'))
  jobs:
  - job: ProdDeployJob
    steps:
    - script: echo "Deploying to PROD environment"
