trigger:
- main

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildApp
    displayName: "Build Application"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'

- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: RunTests
    displayName: "Run Unit Tests"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Test
  jobs:
  - job: DeployApp
    displayName: "Deploy Application"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Deploying application..."
